name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 워크플로 실행

jobs:
  build:
    runs-on: ubuntu-22.04  # 명시적으로 Ubuntu 22.04 사용

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 코드를 체크아웃

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Java 17 사용
          distribution: 'temurin'  # JDK 배포판 설정

      - name: Build with Maven
        run: mvn clean install  # Maven 명령어로 빌드 및 테스트
