name: Java CI Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Maven으로 빌드 (Railway는 자체 배포하므로 테스트만 실행 가능)
      - name: Build and Test with Maven
        run: mvn clean install
        working-directory: wetube  # 'wetube' 디렉터리에서 빌드 실행
