name: Java CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wetube
          MYSQL_USER: wetube
          MYSQL_PASSWORD: 1234
        options: --health-cmd="mysqladmin ping --silent" --health-timeout=5m

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test with Maven
        run: mvn clean install
        working-directory: wetube
