# 이 파일은 Java 프로젝트를 위한 GitHub Actions 설정 파일입니다.
name: Java CI/CD Pipeline # 워크플로 이름

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 워크플로가 실행됨

jobs:
  build:
    runs-on: ubuntu-latest  # 빌드 환경은 최신 Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # GitHub Actions의 코드 체크아웃 액션 사용

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # Java 환경 설정
        with:
          java-version: '17'  # Java 17 사용

      - name: Build with Maven
        run: mvn clean install  # Maven 명령어로 빌드 및 테스트
