name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Maven으로 빌드 (working-directory 설정)
      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: wetube  # 'wetube' 디렉터리에서 Maven 빌드 실행

      # 4. 빌드 결과물 패키징
      - name: Package application
        run: zip -r springBoot-deployment.zip target/*.jar
        working-directory: wetube  # 'wetube' 디렉터리에서 패키징 실행

      # 5. AWS 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 6. Elastic Beanstalk에 배포
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: springBoot
          environment_name: SpringBoot-env
          version_label: springBoot-v1-${{ github.run_number }}
          region: ap-northeast-2
          deployment_package: springBoot-deployment.zip
