name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Maven으로 빌드
      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: wetube  # 수정된 디렉터리 경로

      # 4. 빌드 결과물 저장
       - name: Save build artifact
         uses: actions/upload-artifact@v3
         with:
           name: wetube-artifact
           path: wetube/target/*.jar
 
      # 5. 배포를 위한 패키징
       - name: Package for Elastic Beanstalk
         run: zip -r wetube-deployment.zip target/*.jar
         working-directory: wetube

      # 6. AWS 자격 증명 설정
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ap-northeast-2

      # 7. Elastic Beanstalk에 배포
       - name: Deploy to Elastic Beanstalk
         run: |
           aws elasticbeanstalk create-application-version \
             --application-name wetube \
             --version-label wetube-v1 \
             --source-bundle S3Bucket=my-s3-bucket,S3Key=wetube-deployment.zip

           aws elasticbeanstalk update-environment \
             --environment-name wetube-env \
             --version-label wetube-v1
